# Generated by Django 3.2.18 on 2023-04-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20230416_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='webshop.print')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('prints', models.ManyToManyField(blank=True, to='webshop.CartItem')),
            ],
        ),
    ]
