# Generated by Django 3.2.18 on 2023-04-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0011_printoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='print',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
